apiVersion: skaffold/v1
kind: Config
metadata:
  name: spring-boot-throwaway-branches
build:
  artifacts:
    - image: izeye/spring-boot-throwaway-branches
      jib:
        args: []
deploy:
  kustomize:
    path: kustomize/base

profiles:
  - name: qa
    deploy:
      kustomize:
        path: kustomize/qa