apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

patchesStrategicMerge:
  - update-replicas.yaml
  - use-configmap.yaml

configMapGenerator:
  - name: spring-boot-throwaway-branches-config
    files:
      - application.properties