apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-throwaway-branches
spec:
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: spring-boot-throwaway-branches-config
      containers:
        - name: spring-boot-throwaway-branches
          args:
            - --spring.config.location=/etc/config/application.properties
          volumeMounts:
            - mountPath: /etc/config
              name: config